import Header from "@/components/header/Header";
import { inter } from "@/fonts/fonts";
import { cn } from "@/lib/utils";
import "@/styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.variable,
          "min-h-screen min-w-fit overflow-x-hidden font-inter",
        )}
        style={{ width: "calc(100vw - 12px)" }}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
