import "@//styles/globals.css";
import Header from "@/components/header/Header";
import { inter } from "@/fonts/fonts";
import { cn } from "@/lib/utils";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={cn(
          inter.className,
          "w-screen min-h-screen overflow-x-hidden"
        )}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}

